### ISSUE TITLE
file missing in container

### ISSUE THREAD

**Issue by aztecrex** [waxosuit/waxosuit#17]
I get this trying the first tutorial from the site, in response to the `docker run` command:

```
/waxosuit: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by autodidaddict** [comment]
The automatic deployment for dockerhub is messed up. I will fix this
tomorrow.

**Comment by autodidaddict** [comment]
@aztecrex It looks like my travis build is not pushing the right version of the docker image. The one that's in docker hub right now should do the trick. You can also make your own locally with `make docker` in the project root directory. thanks for reporting this!

**Comment by aztecrex** [comment]
This behavior is back. I'm guessing another manual push will fix? Should this bug remain open until the Travis build is fixed?

**Comment by autodidaddict** [comment]
I'm no longer using the Travis build, the last one I pushed absolutely
contained that file (I watched it add myself).

I'll check again today and see if I can figure out why it's not showing up.

**Comment by autodidaddict** [comment]
I've stopped using Travis entirely. I just re-pushed the image that works so you should be good to go now. I am going to make sure going forward that my automated tests purge the local docker image and use the one from dockerhub to verify. If this happens again, then please re-open.

**Comment by autodidaddict** [comment]
@aztecrex my apologies. I had commented out the travis work on the wrong branch, so the last master branch actually did end up pushing the docker image missing the file. I don't know why Travis builds it wrong, but I've fixed the problem. Sorry for the inconvenience!
