### ISSUE TITLE
NATS SERVER

### ISSUE THREAD

**Issue by joeblew99** [waxosuit/waxosuit#3]
Whats the NATS Streaming Server setup your using.

I really had the same idea as you of using NATS and WASI together and think its the future.

Anyway for newbies if you can put more info in a Make file for what stuff we need under waxosuit to get going would be cool

**Comment by autodidaddict** [comment]
Have you checked out the [tutorials](https://waxosuit.io/getstarted/)?
Right now the NATS client that I'm using doesn't yet support NATS streaming, only regular NATS. All of this stuff is still early days, so I'm counting on feedback from folks like you to let me know what priority I need to work on these things.

Feel free to hit me up on Twitter (KevinHoffman) or my gmail to discuss what you want to do.

**Comment by joeblew99** [comment]
hey Kevin,

Not sure what your email is. Cant find it on the website or anything.
Yeah i got the tutorial running, but was more thinking about NATS durable messaging for cross server scenarios.

I think the API for using NATS Streaming Server is different ?

**Comment by autodidaddict** [comment]
My e-mail is `alothien [at] gmail [dot] com`. It's in nearly every one of the `Cargo.toml` files in the repositories :)

**Comment by joeblew99** [comment]
ok got it. Will shoot you an email
